title: MAHacks
# tagline and description for meta tags
tagline: High School Hackathon in Boston
description: Hackathon in Boston for high schoolers, by high schoolers. We encourage participants to create impactful projects that solve problems.
url: https://mahacks.com # no slash means that all relative URLs that prepend site.url must begin with a slash

permalink: /:title # clean URLs, e.g. /about as opposed to /about.html

include:
  - _redirects

# comment because git sucks
# notes:
# - order of links in this file determines order on website
# - all relative URLs should be appended to site.url, regardless of source file directory

# homepage links
links:
  - name: Register
    url: /register
  - name: About
    url: /about
  - name: Past Events
    url: /past-events
  - name: FAQ
    url: /#faq
  - name: Sponsors
    url: /#sponsors

# homepage images
home_img1_url: /images/1.jpg
home_img2_url: /images/2.jpg

# social media
social_media:
  - name: Facebook
    url: http://facebook.com/mahacks
    icon_url: /icons/facebook-logo.svg
  - name: Medium
    url: http://medium.com/mahacks
    icon_url: /icons/medium-logo.svg
  - name: Twitter
    url: http://twitter.com/ma_hacks
    icon_url: /icons/twitter-logo.svg
  - name: Instagram
    url: http://instagram.com/ma_hacks
    icon_url: /icons/instagram-logo.svg

# sponsors
sponsors:
  - name: Hack Club
    link: https://hackclub.com/bank
    logo_relative_url: /powered-by-hack-club.png
  - name: Flywire
    link: https://www.flywire.com/
    logo_relative_url: /flywire.png
  - name: Rapid7
    link: https://www.rapid7.com
    logo_relative_url: /rapid7.png
  - name: Toast
    link: https://pos.toasttab.com
    logo_relative_url: /toast.png
  - name: Privitar
    link: https://www.privitar.com/
    logo_relative_url: /privitar.jpg
  - name: Repl.it
    link: https://repl.it
    logo_relative_url: /replit.png
