title: MAHacks
# tagline and description for meta tags
tagline: High School Hackathon in Boston
description: Hackathon in Boston for high schoolers, by high schoolers. We encourage participants to create impactful projects that solve problems. December 1-2, 2018, WordStream HQ @ Prudential Center.
url: https://mahacks.com # no slash means that all relative URLs that prepend site.url must begin with a slash

permalink: /:title # clean URLs, e.g. /about as opposed to /about.html

# comment because git sucks
# notes:
# - order of links in this file determines order on website
# - all relative URLs should be appended to site.url, regardless of source file directory

# homepage links
links:
  - name: About
    url: /about
  - name: Past Events
    url: /past-events
  - name: FAQ
    url: /#faq
  - name: Sponsors
    url: /#sponsors

# homepage images
home_img1_url: /1.jpg
home_img2_url: /2.jpg

# social media
social_media:
  - name: Facebook
    url: http://facebook.com/mahacks
    icon_url: /icons/facebook-logo.svg
  - name: Medium
    url: http://medium.com/mahacks
    icon_url: /icons/medium-logo.svg
  - name: Twitter
    url: http://twitter.com/ma_hacks
    icon_url: /icons/twitter-logo.svg
  - name: Instagram
    url: http://instagram.com/ma_hacks
    icon_url: /icons/instagram-logo.svg

# organizers
team:
  - name: Katherine Huang
  - name: Emily Tan
  - name: Aadhya Puttur
  - name: Rebekah Agwunobi
  - name: Walter Shen
  - name: Zhi Wei Gan
  - name: Jolene Pern
  - name: Nina Zhang
  - name: Theo Bleier
alumni:
  - name: Justin Yu
  - name: Max Krieger
  - name: Edward Song
  - name: Nimish Garg
  - name: Jennifer Kim

# sponsors

sponsors:
  - name: Balsamiq
    link: http://balsamiq.com
    logo_relative_url: /balsamiq.png
  - name: Wildbit
    link: http://wildbit.com
    logo_relative_url: /wildbit.png    
  - name: JetBrains
    link: https://jetbrains.com
    logo_relative_url: /jetbrains.png
  - name: Hack Club
    link: https://hackclub.com/bank
    logo_relative_url: /powered-by-hack-club.png
  - name: Particle
    link: https://particle.io
    logo_relative_url: /particle.png
  - name: Dot Tech
    link: https://www.get.tech
    logo_relative_url: /dottech.png
  - name: Wolfram
    link: https://wolfram.com/language/
    logo_relative_url: /wolfram.png
  - name: StickerGiant
    link: https://stickergiant.com/
    logo_relative_url: /stickergiant.png
  - name: RStudio
    link: https://rstudio.com/
    logo_relative_url: /rstudio.png
  - name: Sketch
    link: https://sketchapp.com/
    logo_relative_url: /sketch.png
  - name: AoPS
    link: https://aops.com/
    logo_relative_url: /aops.png


past_sponsors:
  - name: Upstatement
    link: http://upstatement.com
    logo_relative_url: /upstatement.png
  - name: MIT Beaver Works Summer Institute
    link: https://beaverworks.ll.mit.edu/CMS/bw/
    logo_relative_url: /beaverworks.png
  - name: Ultrapress
    link: http://Ultrapress.com
    logo_relative_url: /ultrapress.png
  - name: Gunnar
    link: http://gunnar.com
    logo_relative_url: /gunnar.png
  - name: Accion
    link: http://accion-systems.com
    logo_relative_url: /accion.png
  - name: DataCamp
    link: http://datacamp.com
    logo_relative_url: /datacamp.png
  - name: Commonwealth Institute
    link: http://commonwealthinstitute.org/
    logo_relative_url: /commonwealthinstitute.png
  - name: intellADAPT
    link: http://intelladapt.com/
    logo_relative_url: /intelladapt.png
  - name: National Center for Women & IT
    link: http://ncwit.org/
    logo_relative_url: /ncwit.jpg
  - name: Hacking Pediatrics
    link: http://hackingpediatrics.health/
    logo_relative_url: /hackingpediatrics.JPG
  - name: Quarter Zero
    link: http://quarterzero.com/
    logo_relative_url: /quarterzero.jpg
  - name: Harvard Student Agencies Summer Coding Academy
    link: https://www.summercodingacademy.hsa.net/
    logo_relative_url: /summercodingacademy.png
  - name: StickerYou
    link: https://www.stickeryou.com
    logo_relative_url: /stickeryou.png
  - name: Papa John's
    link: https://www.papajohns.com
    logo_relative_url: /papa-johns.jpg
  - name: Sticker Mule
    link: https://www.stickermule.com
    logo_relative_url: /stickermule.png
  - name: Radix
    link: https://www.get.tech
    logo_relative_url: /radix.png
